// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import MessagePreviewController from "./message_preview_controller"
import ResetFormController from "./reset_form_controller"
import ScrollController from "./scroll_controller"

application.register("message-preview", MessagePreviewController)
application.register("reset-form", ResetFormController)
application.register("scroll", ScrollController)
